expr=term, expr1;
expr1="+",term,expr1|;
term=factor, term1;
term1="*", factor, term1 |;
factor="(", expr , ")" | cislo | "log_", cislo, "-", cislo | "prunik(",obsahPruniku,")";
cislo = hexaCislo | intCislo | binCislo;
hexaCislo = "0x", hexa, {hexa};
binCislo = "b", bin, {bin};
intCislo = "0" | startInt, {int};
startInt = "1"|"2"|"3"|"4"|"5"|"6"|"7"|"8"|"9";
int = "1"|"2"|"3"|"4"|"5"|"6"|"7"|"8"|"9"|"0";
bin = "0"|"1";
hexa = "1"|"2"|"3"|"4"|"5"|"6"|"7"|"8"|"9"|"0"|"A"|"B"|"C"|"D"|"E"|"F";
syntax=expr| array;
array = "[", obsahArray,"]";
obsahArray = hexaCislo, {",", hexaCislo}|intCislo, {",", intCislo}|binCislo, {",", binCislo};
obsahPruniku = array, ",", array, ",", cislo;

